import { ThemeDefinition, ThemeCategory } from './types'

/**
 * All theme definitions for the Thematic Report Builder.
 * Each theme maps to Supabase queries via filters and defines
 * the immersive story section sequence + PDF page plan.
 */

// --- Service Themes (16) ---

const serviceThemes: ThemeDefinition[] = [
  {
    slug: 'health-services',
    title: 'Bwgcolman Healing',
    subtitle: 'Culturally appropriate health and healing on Palm Island',
    category: 'services',
    color: 'from-emerald-600 to-teal-700',
    description: 'The Bwgcolman Healing Service provides culturally appropriate medical and healing services, including social and emotional wellbeing, integrated team care, and the Women\'s Healing Service.',
    filters: {
      storyTags: ['health', 'healing', 'bwgcolman-healing'],
      serviceSlug: 'health-services',
      serviceCategory: 'health',
      quoteThemes: ['health', 'healing', 'wellbeing'],
    },
    sectionSequence: ['hero', 'metrics_bar', 'narrative_intro', 'key_stories', 'elder_quotes', 'photo_gallery', 'vision_forward'],
    pdfPageTypes: [
      { page_number: 1, page_type: 'cover', content_config: { variant: 'service' } },
      { page_number: 2, page_type: 'service_spotlight', content_config: {} },
      { page_number: 3, page_type: 'year_in_numbers', content_config: {} },
      { page_number: 4, page_type: 'story_spread', content_config: { story_index: 0 } },
      { page_number: 5, page_type: 'story_spread', content_config: { story_index: 1 } },
      { page_number: 6, page_type: 'photo_gallery', content_config: {} },
      { page_number: 7, page_type: 'elder_quotes', content_config: {} },
      { page_number: 8, page_type: 'back_cover', content_config: {} },
    ],
  },
  {
    slug: 'family-services',
    title: 'Family Care',
    subtitle: 'Supporting families and strengthening community bonds',
    category: 'services',
    color: 'from-rose-500 to-pink-700',
    description: 'Family Care Service provides comprehensive support for Palm Island families, including placement support, family participation programs, and the Women\'s Service.',
    filters: {
      storyTags: ['family', 'family-care', 'family-services'],
      serviceSlug: 'family-services',
      serviceCategory: 'family',
      quoteThemes: ['family', 'children', 'care'],
    },
    sectionSequence: ['hero', 'metrics_bar', 'narrative_intro', 'key_stories', 'elder_quotes', 'photo_gallery', 'vision_forward'],
    pdfPageTypes: [
      { page_number: 1, page_type: 'cover', content_config: { variant: 'service' } },
      { page_number: 2, page_type: 'service_spotlight', content_config: {} },
      { page_number: 3, page_type: 'year_in_numbers', content_config: {} },
      { page_number: 4, page_type: 'story_spread', content_config: { story_index: 0 } },
      { page_number: 5, page_type: 'story_spread', content_config: { story_index: 1 } },
      { page_number: 6, page_type: 'photo_gallery', content_config: {} },
      { page_number: 7, page_type: 'elder_quotes', content_config: {} },
      { page_number: 8, page_type: 'back_cover', content_config: {} },
    ],
  },
  {
    slug: 'children-family-centre',
    title: 'Children & Family Centre',
    subtitle: 'Nurturing the next generation of Palm Island',
    category: 'services',
    color: 'from-amber-500 to-orange-600',
    description: 'The Children and Family Centre provides early childhood education, family support, and community gathering space. It is the heart of Palm Island\'s investment in children and families.',
    filters: {
      storyTags: ['children', 'cfc', 'early-childhood', 'children-family-centre'],
      serviceSlug: 'children-family-centre',
      serviceCategory: 'family',
      quoteThemes: ['children', 'education', 'early-childhood'],
    },
    sectionSequence: ['hero', 'metrics_bar', 'narrative_intro', 'key_stories', 'elder_quotes', 'photo_gallery', 'vision_forward'],
    pdfPageTypes: [
      { page_number: 1, page_type: 'cover', content_config: { variant: 'service' } },
      { page_number: 2, page_type: 'service_spotlight', content_config: {} },
      { page_number: 3, page_type: 'year_in_numbers', content_config: {} },
      { page_number: 4, page_type: 'story_spread', content_config: { story_index: 0 } },
      { page_number: 5, page_type: 'story_spread', content_config: { story_index: 1 } },
      { page_number: 6, page_type: 'photo_gallery', content_config: {} },
      { page_number: 7, page_type: 'elder_quotes', content_config: {} },
      { page_number: 8, page_type: 'back_cover', content_config: {} },
    ],
  },
  {
    slug: 'delegated-authority',
    title: 'Delegated Authority',
    subtitle: 'Community control over child protection decisions',
    category: 'services',
    color: 'from-violet-600 to-purple-700',
    description: 'The Bwgcolman Way: Empowered and Resilient. PICC\'s historic Delegated Authority means the community now decides care arrangements for children who cannot stay at home, backed by $107.8 million in funding.',
    filters: {
      storyTags: ['delegated-authority', 'child-protection', 'bwgcolman-way'],
      serviceSlug: 'delegated-authority',
      quoteThemes: ['delegated-authority', 'child-protection', 'self-determination'],
      achievementCategory: 'delegated-authority',
    },
    sectionSequence: ['hero', 'metrics_bar', 'narrative_intro', 'key_stories', 'timeline', 'elder_quotes', 'photo_gallery', 'vision_forward'],
    pdfPageTypes: [
      { page_number: 1, page_type: 'cover', content_config: { variant: 'service' } },
      { page_number: 2, page_type: 'service_spotlight', content_config: {} },
      { page_number: 3, page_type: 'year_in_numbers', content_config: {} },
      { page_number: 4, page_type: 'story_spread', content_config: { story_index: 0 } },
      { page_number: 5, page_type: 'story_spread', content_config: { story_index: 1 } },
      { page_number: 6, page_type: 'photo_gallery', content_config: {} },
      { page_number: 7, page_type: 'elder_quotes', content_config: {} },
      { page_number: 8, page_type: 'back_cover', content_config: {} },
    ],
  },
  {
    slug: 'digital-service-centre',
    title: 'Digital Service Centre',
    subtitle: 'Connecting Palm Island to the digital economy',
    category: 'services',
    color: 'from-blue-500 to-indigo-700',
    description: 'The Telstra Digital Service Centre employs 21 Palm Islanders, supporting 50 languages and providing a pathway from TAFE training to Telstra careers. A model for remote Indigenous employment.',
    filters: {
      storyTags: ['digital', 'telstra', 'digital-service-centre'],
      serviceSlug: 'digital-service-centre',
      serviceCategory: 'economic',
      quoteThemes: ['digital', 'employment', 'technology'],
    },
    sectionSequence: ['hero', 'metrics_bar', 'narrative_intro', 'key_stories', 'elder_quotes', 'photo_gallery', 'vision_forward'],
    pdfPageTypes: [
      { page_number: 1, page_type: 'cover', content_config: { variant: 'service' } },
      { page_number: 2, page_type: 'service_spotlight', content_config: {} },
      { page_number: 3, page_type: 'year_in_numbers', content_config: {} },
      { page_number: 4, page_type: 'story_spread', content_config: { story_index: 0 } },
      { page_number: 5, page_type: 'story_spread', content_config: { story_index: 1 } },
      { page_number: 6, page_type: 'photo_gallery', content_config: {} },
      { page_number: 7, page_type: 'elder_quotes', content_config: {} },
      { page_number: 8, page_type: 'back_cover', content_config: {} },
    ],
  },
  {
    slug: 'justice-services',
    title: 'Justice Services',
    subtitle: 'Community-led justice and diversion programs',
    category: 'services',
    color: 'from-slate-600 to-gray-800',
    description: 'The Community Justice Group and Diversionary Service provide culturally appropriate justice pathways, keeping people connected to community and reducing incarceration.',
    filters: {
      storyTags: ['justice', 'diversion', 'justice-services'],
      serviceSlug: 'justice-services',
      serviceCategory: 'justice',
      quoteThemes: ['justice', 'diversion', 'community-safety'],
    },
    sectionSequence: ['hero', 'metrics_bar', 'narrative_intro', 'key_stories', 'elder_quotes', 'photo_gallery', 'vision_forward'],
    pdfPageTypes: [
      { page_number: 1, page_type: 'cover', content_config: { variant: 'service' } },
      { page_number: 2, page_type: 'service_spotlight', content_config: {} },
      { page_number: 3, page_type: 'year_in_numbers', content_config: {} },
      { page_number: 4, page_type: 'story_spread', content_config: { story_index: 0 } },
      { page_number: 5, page_type: 'story_spread', content_config: { story_index: 1 } },
      { page_number: 6, page_type: 'photo_gallery', content_config: {} },
      { page_number: 7, page_type: 'elder_quotes', content_config: {} },
      { page_number: 8, page_type: 'back_cover', content_config: {} },
    ],
  },
  {
    slug: 'crisis-services',
    title: 'Crisis & Safety',
    subtitle: 'Safe Haven and Safe House keeping families safe',
    category: 'services',
    color: 'from-red-600 to-rose-800',
    description: 'The Safe Haven Service supported 1,187 children in 2024, and the Safe House provided 1,439 placement nights. These services are the safety net for Palm Island\'s most vulnerable.',
    filters: {
      storyTags: ['crisis', 'safe-haven', 'safe-house', 'crisis-services'],
      serviceSlug: 'crisis-services',
      serviceCategory: 'crisis',
      quoteThemes: ['safety', 'crisis', 'protection'],
    },
    sectionSequence: ['hero', 'metrics_bar', 'narrative_intro', 'key_stories', 'elder_quotes', 'photo_gallery', 'vision_forward'],
    pdfPageTypes: [
      { page_number: 1, page_type: 'cover', content_config: { variant: 'service' } },
      { page_number: 2, page_type: 'service_spotlight', content_config: {} },
      { page_number: 3, page_type: 'year_in_numbers', content_config: {} },
      { page_number: 4, page_type: 'story_spread', content_config: { story_index: 0 } },
      { page_number: 5, page_type: 'story_spread', content_config: { story_index: 1 } },
      { page_number: 6, page_type: 'photo_gallery', content_config: {} },
      { page_number: 7, page_type: 'elder_quotes', content_config: {} },
      { page_number: 8, page_type: 'back_cover', content_config: {} },
    ],
  },
  {
    slug: 'youth-services',
    title: 'Youth Programs',
    subtitle: 'Empowering Palm Island\'s young people',
    category: 'services',
    color: 'from-cyan-500 to-blue-600',
    description: 'Youth Services provides programs, activities, and support for young Palm Islanders, building confidence, cultural connection, and pathways to opportunity.',
    filters: {
      storyTags: ['youth', 'young-people', 'youth-services'],
      serviceSlug: 'youth-services',
      serviceCategory: 'youth',
      quoteThemes: ['youth', 'young-people', 'future'],
    },
    sectionSequence: ['hero', 'metrics_bar', 'narrative_intro', 'key_stories', 'elder_quotes', 'photo_gallery', 'vision_forward'],
    pdfPageTypes: [
      { page_number: 1, page_type: 'cover', content_config: { variant: 'service' } },
      { page_number: 2, page_type: 'service_spotlight', content_config: {} },
      { page_number: 3, page_type: 'year_in_numbers', content_config: {} },
      { page_number: 4, page_type: 'story_spread', content_config: { story_index: 0 } },
      { page_number: 5, page_type: 'story_spread', content_config: { story_index: 1 } },
      { page_number: 6, page_type: 'photo_gallery', content_config: {} },
      { page_number: 7, page_type: 'elder_quotes', content_config: {} },
      { page_number: 8, page_type: 'back_cover', content_config: {} },
    ],
  },
  {
    slug: 'womens-healing',
    title: 'Women\'s Healing',
    subtitle: 'Gender-specific healing and empowerment',
    category: 'services',
    color: 'from-fuchsia-500 to-pink-700',
    description: 'The Women\'s Healing Service operates across Palm Island and Townsville, providing gender-specific healing, support, and empowerment for women and girls.',
    filters: {
      storyTags: ['women', 'womens-healing', 'womens-service'],
      serviceCategory: 'health',
      quoteThemes: ['women', 'healing', 'empowerment'],
    },
    sectionSequence: ['hero', 'metrics_bar', 'narrative_intro', 'key_stories', 'elder_quotes', 'photo_gallery', 'vision_forward'],
    pdfPageTypes: [
      { page_number: 1, page_type: 'cover', content_config: { variant: 'service' } },
      { page_number: 2, page_type: 'service_spotlight', content_config: {} },
      { page_number: 3, page_type: 'year_in_numbers', content_config: {} },
      { page_number: 4, page_type: 'story_spread', content_config: { story_index: 0 } },
      { page_number: 5, page_type: 'story_spread', content_config: { story_index: 1 } },
      { page_number: 6, page_type: 'photo_gallery', content_config: {} },
      { page_number: 7, page_type: 'elder_quotes', content_config: {} },
      { page_number: 8, page_type: 'back_cover', content_config: {} },
    ],
  },
  {
    slug: 'ndis-connector',
    title: 'NDIS Connector',
    subtitle: 'Helping Palm Islanders access disability services',
    category: 'services',
    color: 'from-teal-500 to-emerald-700',
    description: 'The Remote Community Connector helps Palm Islanders navigate and access NDIS services, operating from the new Retail Centre on Palm Island and Aitkenvale in Townsville.',
    filters: {
      storyTags: ['ndis', 'disability', 'ndis-connector'],
      serviceCategory: 'disability',
      quoteThemes: ['ndis', 'disability', 'access'],
    },
    sectionSequence: ['hero', 'metrics_bar', 'narrative_intro', 'key_stories', 'photo_gallery', 'vision_forward'],
    pdfPageTypes: [
      { page_number: 1, page_type: 'cover', content_config: { variant: 'service' } },
      { page_number: 2, page_type: 'service_spotlight', content_config: {} },
      { page_number: 3, page_type: 'year_in_numbers', content_config: {} },
      { page_number: 4, page_type: 'story_spread', content_config: { story_index: 0 } },
      { page_number: 5, page_type: 'story_spread', content_config: { story_index: 1 } },
      { page_number: 6, page_type: 'photo_gallery', content_config: {} },
      { page_number: 7, page_type: 'elder_quotes', content_config: {} },
      { page_number: 8, page_type: 'back_cover', content_config: {} },
    ],
  },
  {
    slug: 'social-enterprises',
    title: 'Social Enterprises',
    subtitle: 'Building economic independence on Palm Island',
    category: 'services',
    color: 'from-yellow-500 to-amber-700',
    description: 'PICC\'s Social Enterprises employ 44 Palm Islanders across various economic development programs, creating local jobs and building economic independence for the community.',
    filters: {
      storyTags: ['social-enterprise', 'economic', 'employment'],
      serviceCategory: 'economic',
      quoteThemes: ['employment', 'economic', 'enterprise'],
    },
    sectionSequence: ['hero', 'metrics_bar', 'narrative_intro', 'key_stories', 'photo_gallery', 'vision_forward'],
    pdfPageTypes: [
      { page_number: 1, page_type: 'cover', content_config: { variant: 'service' } },
      { page_number: 2, page_type: 'service_spotlight', content_config: {} },
      { page_number: 3, page_type: 'year_in_numbers', content_config: {} },
      { page_number: 4, page_type: 'story_spread', content_config: { story_index: 0 } },
      { page_number: 5, page_type: 'story_spread', content_config: { story_index: 1 } },
      { page_number: 6, page_type: 'photo_gallery', content_config: {} },
      { page_number: 7, page_type: 'elder_quotes', content_config: {} },
      { page_number: 8, page_type: 'back_cover', content_config: {} },
    ],
  },
  {
    slug: 'domestic-violence',
    title: 'DFV Prevention',
    subtitle: 'Specialist domestic and family violence response',
    category: 'services',
    color: 'from-orange-600 to-red-700',
    description: 'The Specialist Domestic and Family Violence Service provides prevention, intervention, and ongoing support for individuals and families experiencing domestic and family violence.',
    filters: {
      storyTags: ['dfv', 'domestic-violence', 'family-violence', 'safety'],
      serviceCategory: 'safety',
      quoteThemes: ['safety', 'violence-prevention', 'healing'],
    },
    sectionSequence: ['hero', 'metrics_bar', 'narrative_intro', 'key_stories', 'elder_quotes', 'photo_gallery', 'vision_forward'],
    pdfPageTypes: [
      { page_number: 1, page_type: 'cover', content_config: { variant: 'service' } },
      { page_number: 2, page_type: 'service_spotlight', content_config: {} },
      { page_number: 3, page_type: 'year_in_numbers', content_config: {} },
      { page_number: 4, page_type: 'story_spread', content_config: { story_index: 0 } },
      { page_number: 5, page_type: 'story_spread', content_config: { story_index: 1 } },
      { page_number: 6, page_type: 'photo_gallery', content_config: {} },
      { page_number: 7, page_type: 'elder_quotes', content_config: {} },
      { page_number: 8, page_type: 'back_cover', content_config: {} },
    ],
  },
  {
    slug: 'medical-services',
    title: 'Medical Services',
    subtitle: 'Primary healthcare for Palm Island',
    category: 'services',
    color: 'from-sky-500 to-blue-700',
    description: 'Primary healthcare including GP services, child health, maternal health, and the First 1,000 Days Program supporting families during the critical early years of a child\'s life.',
    filters: {
      storyTags: ['medical', 'gp', 'primary-health', 'first-1000-days'],
      serviceCategory: 'health',
      quoteThemes: ['health', 'medical', 'maternal'],
    },
    sectionSequence: ['hero', 'metrics_bar', 'narrative_intro', 'key_stories', 'elder_quotes', 'photo_gallery', 'vision_forward'],
    pdfPageTypes: [
      { page_number: 1, page_type: 'cover', content_config: { variant: 'service' } },
      { page_number: 2, page_type: 'service_spotlight', content_config: {} },
      { page_number: 3, page_type: 'year_in_numbers', content_config: {} },
      { page_number: 4, page_type: 'story_spread', content_config: { story_index: 0 } },
      { page_number: 5, page_type: 'story_spread', content_config: { story_index: 1 } },
      { page_number: 6, page_type: 'photo_gallery', content_config: {} },
      { page_number: 7, page_type: 'elder_quotes', content_config: {} },
      { page_number: 8, page_type: 'back_cover', content_config: {} },
    ],
  },
  {
    slug: 'sewb',
    title: 'Social & Emotional Wellbeing',
    subtitle: 'Holistic mental health and cultural healing',
    category: 'services',
    color: 'from-green-500 to-emerald-700',
    description: 'Social and Emotional Wellbeing (SEWB) services provide culturally grounded mental health support, connecting people with healing through culture, country, and community.',
    filters: {
      storyTags: ['sewb', 'mental-health', 'wellbeing', 'social-emotional'],
      serviceCategory: 'health',
      quoteThemes: ['wellbeing', 'mental-health', 'healing'],
    },
    sectionSequence: ['hero', 'metrics_bar', 'narrative_intro', 'key_stories', 'elder_quotes', 'photo_gallery', 'vision_forward'],
    pdfPageTypes: [
      { page_number: 1, page_type: 'cover', content_config: { variant: 'service' } },
      { page_number: 2, page_type: 'service_spotlight', content_config: {} },
      { page_number: 3, page_type: 'year_in_numbers', content_config: {} },
      { page_number: 4, page_type: 'story_spread', content_config: { story_index: 0 } },
      { page_number: 5, page_type: 'story_spread', content_config: { story_index: 1 } },
      { page_number: 6, page_type: 'photo_gallery', content_config: {} },
      { page_number: 7, page_type: 'elder_quotes', content_config: {} },
      { page_number: 8, page_type: 'back_cover', content_config: {} },
    ],
  },
  {
    slug: 'integrated-team-care',
    title: 'Integrated Team Care',
    subtitle: 'Coordinated chronic disease management',
    category: 'services',
    color: 'from-lime-500 to-green-700',
    description: 'Integrated Team Care provides coordinated support for chronic disease management, working alongside GPs and specialists to ensure Palm Islanders receive consistent, culturally appropriate care.',
    filters: {
      storyTags: ['itc', 'integrated-care', 'chronic-disease'],
      serviceCategory: 'health',
      quoteThemes: ['health', 'chronic-disease', 'care'],
    },
    sectionSequence: ['hero', 'metrics_bar', 'narrative_intro', 'key_stories', 'photo_gallery', 'vision_forward'],
    pdfPageTypes: [
      { page_number: 1, page_type: 'cover', content_config: { variant: 'service' } },
      { page_number: 2, page_type: 'service_spotlight', content_config: {} },
      { page_number: 3, page_type: 'year_in_numbers', content_config: {} },
      { page_number: 4, page_type: 'story_spread', content_config: { story_index: 0 } },
      { page_number: 5, page_type: 'story_spread', content_config: { story_index: 1 } },
      { page_number: 6, page_type: 'photo_gallery', content_config: {} },
      { page_number: 7, page_type: 'elder_quotes', content_config: {} },
      { page_number: 8, page_type: 'back_cover', content_config: {} },
    ],
  },
  {
    slug: 'family-wellbeing',
    title: 'Family Wellbeing Centre',
    subtitle: 'Wellness support for Palm Island families',
    category: 'services',
    color: 'from-pink-400 to-rose-600',
    description: 'The Family Wellbeing Centre provides holistic wellness support for families, combining cultural practices with contemporary support models to strengthen family resilience.',
    filters: {
      storyTags: ['family-wellbeing', 'wellness', 'family-support'],
      serviceCategory: 'health',
      quoteThemes: ['family', 'wellbeing', 'support'],
    },
    sectionSequence: ['hero', 'metrics_bar', 'narrative_intro', 'key_stories', 'photo_gallery', 'vision_forward'],
    pdfPageTypes: [
      { page_number: 1, page_type: 'cover', content_config: { variant: 'service' } },
      { page_number: 2, page_type: 'service_spotlight', content_config: {} },
      { page_number: 3, page_type: 'year_in_numbers', content_config: {} },
      { page_number: 4, page_type: 'story_spread', content_config: { story_index: 0 } },
      { page_number: 5, page_type: 'story_spread', content_config: { story_index: 1 } },
      { page_number: 6, page_type: 'photo_gallery', content_config: {} },
      { page_number: 7, page_type: 'elder_quotes', content_config: {} },
      { page_number: 8, page_type: 'back_cover', content_config: {} },
    ],
  },
]

// --- Innovation Themes (6) ---

const innovationThemes: ThemeDefinition[] = [
  {
    slug: 'photo-studio',
    title: 'The Photo Studio',
    subtitle: 'A professional portrait studio run by Palm Islanders',
    category: 'innovation',
    color: 'from-amber-500 to-yellow-700',
    description: 'The Photo Studio is a first-of-its-kind professional portrait facility on Palm Island, created to capture the dignity and beauty of Elders and community members. Over 1,885 photos have been taken.',
    filters: {
      storyTags: ['photo-studio', 'photography', 'portraits', 'project:photo-studio'],
      quoteThemes: ['photo-studio', 'photography', 'portraits'],
    },
    sectionSequence: ['hero', 'metrics_bar', 'narrative_intro', 'key_stories', 'photo_gallery', 'parallax_divider', 'elder_quotes', 'vision_forward'],
    pdfPageTypes: [
      { page_number: 1, page_type: 'cover', content_config: { variant: 'innovation' } },
      { page_number: 2, page_type: 'innovation', content_config: {} },
      { page_number: 3, page_type: 'story_spread', content_config: { story_index: 0 } },
      { page_number: 4, page_type: 'photo_gallery', content_config: {} },
      { page_number: 5, page_type: 'highlights', content_config: {} },
      { page_number: 6, page_type: 'back_cover', content_config: {} },
    ],
  },
  {
    slug: 'the-station',
    title: 'The Station',
    subtitle: 'Community media hub and storytelling centre',
    category: 'innovation',
    color: 'from-indigo-500 to-violet-700',
    description: 'The Station is Palm Island\'s emerging media and storytelling hub, where community members can record, edit, and share their stories using professional equipment.',
    filters: {
      storyTags: ['the-station', 'media-hub', 'storytelling', 'project:the-station'],
      quoteThemes: ['storytelling', 'media', 'voice'],
    },
    sectionSequence: ['hero', 'narrative_intro', 'key_stories', 'photo_gallery', 'elder_quotes', 'vision_forward'],
    pdfPageTypes: [
      { page_number: 1, page_type: 'cover', content_config: { variant: 'innovation' } },
      { page_number: 2, page_type: 'innovation', content_config: {} },
      { page_number: 3, page_type: 'story_spread', content_config: { story_index: 0 } },
      { page_number: 4, page_type: 'photo_gallery', content_config: {} },
      { page_number: 5, page_type: 'highlights', content_config: {} },
      { page_number: 6, page_type: 'back_cover', content_config: {} },
    ],
  },
  {
    slug: 'hull-river',
    title: 'Hull River Story',
    subtitle: 'Walking back to where it all began',
    category: 'innovation',
    color: 'from-stone-600 to-stone-800',
    description: 'The Hull River Aboriginal Settlement was destroyed by a cyclone in 1918, and survivors were relocated to Palm Island. This project documents the journey of Elders walking back to Hull River to reconnect with their history.',
    filters: {
      storyTags: ['hull-river', 'history', 'elders-trip', 'project:hull-river'],
      quoteThemes: ['hull-river', 'history', 'country', 'healing'],
    },
    sectionSequence: ['hero', 'narrative_intro', 'timeline', 'key_stories', 'photo_gallery', 'parallax_divider', 'elder_quotes', 'vision_forward'],
    pdfPageTypes: [
      { page_number: 1, page_type: 'cover', content_config: { variant: 'innovation' } },
      { page_number: 2, page_type: 'innovation', content_config: {} },
      { page_number: 3, page_type: 'story_spread', content_config: { story_index: 0 } },
      { page_number: 4, page_type: 'photo_gallery', content_config: {} },
      { page_number: 5, page_type: 'highlights', content_config: {} },
      { page_number: 6, page_type: 'back_cover', content_config: {} },
    ],
  },
  {
    slug: 'on-country-server',
    title: 'On-Country Server',
    subtitle: 'Sovereign data infrastructure on Palm Island',
    category: 'innovation',
    color: 'from-emerald-600 to-green-800',
    description: 'An on-country local server that ensures Palm Island\'s data sovereignty. Community data stays on community land, accessible even when internet connectivity is limited.',
    filters: {
      storyTags: ['local-server', 'data-sovereignty', 'infrastructure', 'project:local-server'],
      quoteThemes: ['technology', 'data-sovereignty', 'innovation'],
    },
    sectionSequence: ['hero', 'narrative_intro', 'key_stories', 'photo_gallery', 'vision_forward'],
    pdfPageTypes: [
      { page_number: 1, page_type: 'cover', content_config: { variant: 'innovation' } },
      { page_number: 2, page_type: 'innovation', content_config: {} },
      { page_number: 3, page_type: 'story_spread', content_config: { story_index: 0 } },
      { page_number: 4, page_type: 'photo_gallery', content_config: {} },
      { page_number: 5, page_type: 'highlights', content_config: {} },
      { page_number: 6, page_type: 'back_cover', content_config: {} },
    ],
  },
  {
    slug: 'ai-reports',
    title: 'AI-Powered Reports',
    subtitle: 'Using AI to tell community stories at scale',
    category: 'innovation',
    color: 'from-cyan-500 to-teal-700',
    description: 'PICC uses AI to automate annual report generation, pulling real data from 16+ services to create professional reports that tell the community\'s story accurately and beautifully.',
    filters: {
      storyTags: ['ai', 'annual-report', 'automation', 'project:ai-reports'],
      quoteThemes: ['innovation', 'technology', 'reporting'],
    },
    sectionSequence: ['hero', 'narrative_intro', 'key_stories', 'photo_gallery', 'vision_forward'],
    pdfPageTypes: [
      { page_number: 1, page_type: 'cover', content_config: { variant: 'innovation' } },
      { page_number: 2, page_type: 'innovation', content_config: {} },
      { page_number: 3, page_type: 'story_spread', content_config: { story_index: 0 } },
      { page_number: 4, page_type: 'photo_gallery', content_config: {} },
      { page_number: 5, page_type: 'highlights', content_config: {} },
      { page_number: 6, page_type: 'back_cover', content_config: {} },
    ],
  },
  {
    slug: 'community-stories',
    title: 'Community Storytelling',
    subtitle: 'Preserving voices for generations to come',
    category: 'innovation',
    color: 'from-orange-500 to-red-700',
    description: 'A systematic approach to collecting, preserving, and sharing community stories. Over 77 stories have been collected, capturing the lived experience of Palm Islanders in their own words.',
    filters: {
      storyTags: ['storytelling', 'community-voice', 'oral-history', 'project:stories'],
      quoteThemes: ['storytelling', 'voice', 'community'],
    },
    sectionSequence: ['hero', 'metrics_bar', 'narrative_intro', 'key_stories', 'elder_quotes', 'photo_gallery', 'vision_forward'],
    pdfPageTypes: [
      { page_number: 1, page_type: 'cover', content_config: { variant: 'innovation' } },
      { page_number: 2, page_type: 'innovation', content_config: {} },
      { page_number: 3, page_type: 'story_spread', content_config: { story_index: 0 } },
      { page_number: 4, page_type: 'photo_gallery', content_config: {} },
      { page_number: 5, page_type: 'highlights', content_config: {} },
      { page_number: 6, page_type: 'back_cover', content_config: {} },
    ],
  },
]

// --- Era Themes (4) ---

const eraThemes: ThemeDefinition[] = [
  {
    slug: 'foundation-era',
    title: 'Foundation Years',
    subtitle: '2009-2012: Building from the ground up',
    category: 'eras',
    color: 'from-stone-500 to-stone-700',
    description: 'The Foundation Era saw PICC establish itself as a community organization, laying the groundwork for service delivery and community governance on Palm Island.',
    filters: {
      fiscalYearRange: { from: 2009, to: 2012 },
      achievementCategory: 'foundation',
    },
    sectionSequence: ['hero', 'metrics_bar', 'narrative_intro', 'timeline', 'key_stories', 'photo_gallery', 'vision_forward'],
    pdfPageTypes: [
      { page_number: 1, page_type: 'cover', content_config: { variant: 'era' } },
      { page_number: 2, page_type: 'year_in_numbers', content_config: {} },
      { page_number: 3, page_type: 'highlights', content_config: {} },
      { page_number: 4, page_type: 'story_spread', content_config: { story_index: 0 } },
      { page_number: 5, page_type: 'governance', content_config: {} },
      { page_number: 6, page_type: 'photo_gallery', content_config: {} },
      { page_number: 7, page_type: 'back_cover', content_config: {} },
    ],
  },
  {
    slug: 'growth-era',
    title: 'Growth & Expansion',
    subtitle: '2013-2018: Scaling services across the community',
    category: 'eras',
    color: 'from-green-600 to-emerald-800',
    description: 'During the Growth Era, PICC expanded from a handful of services to over a dozen, growing staff numbers significantly and deepening the organization\'s reach across Palm Island.',
    filters: {
      fiscalYearRange: { from: 2013, to: 2018 },
      achievementCategory: 'growth',
    },
    sectionSequence: ['hero', 'metrics_bar', 'narrative_intro', 'timeline', 'key_stories', 'photo_gallery', 'vision_forward'],
    pdfPageTypes: [
      { page_number: 1, page_type: 'cover', content_config: { variant: 'era' } },
      { page_number: 2, page_type: 'year_in_numbers', content_config: {} },
      { page_number: 3, page_type: 'highlights', content_config: {} },
      { page_number: 4, page_type: 'story_spread', content_config: { story_index: 0 } },
      { page_number: 5, page_type: 'governance', content_config: {} },
      { page_number: 6, page_type: 'photo_gallery', content_config: {} },
      { page_number: 7, page_type: 'back_cover', content_config: {} },
    ],
  },
  {
    slug: 'transition-era',
    title: 'Transition to Control',
    subtitle: '2019-2020: Preparing for community ownership',
    category: 'eras',
    color: 'from-amber-600 to-orange-800',
    description: 'The Transition Era was the critical period where PICC prepared for full community control, navigating COVID-19 while building governance capacity and securing the Delegated Authority framework.',
    filters: {
      fiscalYearRange: { from: 2019, to: 2020 },
      achievementCategory: 'transition',
    },
    sectionSequence: ['hero', 'metrics_bar', 'narrative_intro', 'timeline', 'key_stories', 'photo_gallery', 'vision_forward'],
    pdfPageTypes: [
      { page_number: 1, page_type: 'cover', content_config: { variant: 'era' } },
      { page_number: 2, page_type: 'year_in_numbers', content_config: {} },
      { page_number: 3, page_type: 'highlights', content_config: {} },
      { page_number: 4, page_type: 'story_spread', content_config: { story_index: 0 } },
      { page_number: 5, page_type: 'governance', content_config: {} },
      { page_number: 6, page_type: 'photo_gallery', content_config: {} },
      { page_number: 7, page_type: 'back_cover', content_config: {} },
    ],
  },
  {
    slug: 'community-led-era',
    title: 'Community-Led',
    subtitle: '2021-Present: Self-determination in action',
    category: 'eras',
    color: 'from-picc-red to-picc-ochre',
    description: 'Since transitioning to full community control on 30 September 2021, PICC has grown to over 200 staff, secured the historic Delegated Authority, and launched innovative projects that are transforming Palm Island.',
    filters: {
      fiscalYearRange: { from: 2021, to: 2026 },
      achievementCategory: 'community-led',
    },
    sectionSequence: ['hero', 'metrics_bar', 'narrative_intro', 'timeline', 'key_stories', 'elder_quotes', 'photo_gallery', 'parallax_divider', 'vision_forward'],
    pdfPageTypes: [
      { page_number: 1, page_type: 'cover', content_config: { variant: 'era' } },
      { page_number: 2, page_type: 'year_in_numbers', content_config: {} },
      { page_number: 3, page_type: 'highlights', content_config: {} },
      { page_number: 4, page_type: 'story_spread', content_config: { story_index: 0 } },
      { page_number: 5, page_type: 'governance', content_config: {} },
      { page_number: 6, page_type: 'photo_gallery', content_config: {} },
      { page_number: 7, page_type: 'back_cover', content_config: {} },
    ],
  },
]

// --- Vision Themes (2) ---

const visionThemes: ThemeDefinition[] = [
  {
    slug: '20-year-vision',
    title: '20-Year Vision',
    subtitle: 'The full journey from 2009 to 2029 and beyond',
    category: 'vision',
    color: 'from-picc-red via-picc-ochre to-picc-earth',
    description: 'The complete arc of Palm Island Community Company — from a small community organisation to a powerhouse of self-determination. This is the story of how a community took control of its own future.',
    filters: {
      storyTags: ['vision', '20-years', 'milestone', 'self-determination'],
      quoteThemes: ['vision', 'future', 'self-determination', 'community'],
    },
    sectionSequence: ['hero', 'metrics_bar', 'narrative_intro', 'timeline', 'key_stories', 'parallax_divider', 'elder_quotes', 'photo_gallery', 'vision_forward'],
    pdfPageTypes: [
      { page_number: 1, page_type: 'cover', content_config: { variant: 'vision' } },
      { page_number: 2, page_type: 'acknowledgement', content_config: {} },
      { page_number: 3, page_type: 'year_in_numbers', content_config: {} },
      { page_number: 4, page_type: 'highlights', content_config: {} },
      { page_number: 5, page_type: 'story_spread', content_config: { story_index: 0 } },
      { page_number: 6, page_type: 'story_spread', content_config: { story_index: 1 } },
      { page_number: 7, page_type: 'innovation', content_config: {} },
      { page_number: 8, page_type: 'photo_gallery', content_config: {} },
      { page_number: 9, page_type: 'elder_quotes', content_config: {} },
      { page_number: 10, page_type: 'back_cover', content_config: {} },
    ],
  },
  {
    slug: 'next-decade',
    title: 'Next Decade 2026-2035',
    subtitle: 'A prospectus for Palm Island\'s future',
    category: 'vision',
    color: 'from-blue-600 via-indigo-600 to-violet-700',
    description: 'The next ten years will see PICC grow into a fully sovereign community organisation. This prospectus outlines the vision for expanded services, economic independence, and cultural renaissance.',
    filters: {
      storyTags: ['future', 'next-decade', 'prospectus', '2026-2035'],
      quoteThemes: ['future', 'vision', 'next-generation'],
    },
    sectionSequence: ['hero', 'metrics_bar', 'narrative_intro', 'key_stories', 'parallax_divider', 'elder_quotes', 'photo_gallery', 'timeline', 'vision_forward'],
    pdfPageTypes: [
      { page_number: 1, page_type: 'cover', content_config: { variant: 'vision' } },
      { page_number: 2, page_type: 'acknowledgement', content_config: {} },
      { page_number: 3, page_type: 'year_in_numbers', content_config: {} },
      { page_number: 4, page_type: 'highlights', content_config: {} },
      { page_number: 5, page_type: 'story_spread', content_config: { story_index: 0 } },
      { page_number: 6, page_type: 'story_spread', content_config: { story_index: 1 } },
      { page_number: 7, page_type: 'innovation', content_config: {} },
      { page_number: 8, page_type: 'photo_gallery', content_config: {} },
      { page_number: 9, page_type: 'elder_quotes', content_config: {} },
      { page_number: 10, page_type: 'back_cover', content_config: {} },
    ],
  },
]

// --- Exports ---

export const ALL_THEMES: ThemeDefinition[] = [
  ...serviceThemes,
  ...innovationThemes,
  ...eraThemes,
  ...visionThemes,
]

export function getThemeBySlug(slug: string): ThemeDefinition | undefined {
  return ALL_THEMES.find(t => t.slug === slug)
}

export function getThemesByCategory(category: ThemeCategory): ThemeDefinition[] {
  return ALL_THEMES.filter(t => t.category === category)
}

export const THEME_CATEGORY_LABELS: Record<ThemeCategory, string> = {
  services: 'Services',
  innovation: 'Innovation',
  eras: 'Eras',
  vision: 'Vision',
}

export const THEME_CATEGORY_ORDER: ThemeCategory[] = ['services', 'innovation', 'eras', 'vision']
