/**
 * Quote library — loads the EL elder quotes from the local JSON dump
 * (scripts/reports/elders-bios-quotes-*.json) and exposes them with
 * annual-report-friendly filtering.
 *
 * Why local file vs API: EL doesn't expose a public quote endpoint
 * for PICC yet. The local dumps are generated by the elder-bio script
 * and contain the canonical quote_text + context + theme + sentiment +
 * suggested_for_report flag.
 *
 * For non-elder voices (Rachel, Henry, etc.), use placeholder quotes
 * derived from their bio until EL exposes their full quote stream.
 */
import { readdir, readFile } from 'node:fs/promises'
import { join } from 'node:path'

export interface ELQuote {
  id: string
  quote_text: string
  attribution: string
  context: string | null
  theme: string | null
  sentiment: string | null
  impact_area: string | null
  is_validated: boolean
  suggested_for_report: boolean
  storyteller_slug: string
  storyteller_name: string
}

const SLUG_MAP: Record<string, string> = {
  'Allan Palm Island': 'allan-palm-island',
  'Aunty Ethel': 'aunty-ethel-taylor-robertson',
  'Cyndel': 'cyndel-louise-pryor',
  'Elsa': 'elsa-watson',
  'Gurtrude': 'gurtrude-grace-richardson',
  'Marjoyie': 'marjoyie-burns',
  'Uncle Frank': 'uncle-frank-daniel-anderson',
  'Winni': 'winifred-obah',
  'Aunty Iris May Whitey': 'aunty-iris-may-whitey',
  'Aunty Iris': 'aunty-iris-may-whitey',
  'Iris': 'aunty-iris-may-whitey',
  'Henry Doyle': 'henry-doyle',
  'Rachel Atkinson': 'rachel-atkinson',
  'Luella Bligh': 'luella-bligh',
}

export async function loadAllQuotes(): Promise<ELQuote[]> {
  const dir = join(process.cwd(), 'scripts', 'reports')
  let files: string[] = []
  try {
    files = (await readdir(dir)).filter((f) => /elders-bios-quotes.*\.json/.test(f))
  } catch {
    return []
  }
  if (files.length === 0) return []

  // Latest file (sorted ascending; the newest sorts last)
  const latest = files.sort().pop()!
  const data = JSON.parse(await readFile(join(dir, latest), 'utf8')) as {
    elders: Array<{
      name: string
      quotes: Array<{
        id: string
        quote_text: string
        attribution: string
        context: string | null
        theme: string | null
        sentiment: string | null
        impact_area: string | null
        is_validated: boolean
        suggested_for_report: boolean
      }>
    }>
  }

  const out: ELQuote[] = []
  for (const elder of data.elders) {
    const slug = SLUG_MAP[elder.name] ?? elder.name.toLowerCase().replace(/\s+/g, '-')
    for (const q of elder.quotes) {
      out.push({
        id: q.id,
        quote_text: q.quote_text,
        attribution: q.attribution ?? elder.name,
        context: q.context,
        theme: q.theme,
        sentiment: q.sentiment,
        impact_area: q.impact_area,
        is_validated: q.is_validated,
        suggested_for_report: q.suggested_for_report,
        storyteller_slug: slug,
        storyteller_name: elder.name,
      })
    }
  }
  return out
}

/**
 * Score a quote for annual-report use.
 * Higher score = better for an annual report context.
 *
 * Heuristics (additive):
 *   + 30 if suggested_for_report
 *   + 20 if validated
 *   + 15 if length is in the sweet spot (60–180 chars)
 *   + 10 if theme matches a "high-value" annual report theme
 *   - 10 if length too short or too long
 *   - 20 if appears to need cultural review (sensitive context words)
 */
export function scoreForReport(q: ELQuote): number {
  let s = 0
  if (q.suggested_for_report) s += 30
  if (q.is_validated) s += 20
  const len = q.quote_text.length
  if (len >= 60 && len <= 180) s += 15
  else if (len < 30 || len > 280) s -= 10
  const goodThemes = ['community', 'culture', 'connection', 'resilience', 'achievement', 'youth']
  if (q.theme && goodThemes.includes(q.theme)) s += 10
  return s
}

export const ANNUAL_REPORT_QUOTE_PRINCIPLES = `
PICK QUOTES THAT:
1. Speak to community continuity — not personal grievance alone
2. Name a place, person, or service if natural
3. Are 12–30 words for tile use, 20–60 words for pull quotes
4. Have been validated OR flagged suggested_for_report
5. Pair with a theme that matches the spread's section
6. Pass cultural review (no Sorry Business names without consent)
7. Read out loud as the speaker — would they recognise it?

REJECT QUOTES THAT:
- Use jargon only insiders understand
- Single out an individual without their consent
- Air operational complaints meant for staff meetings
- Are uncited paraphrases (always exact words from EL transcript)
- Strip context that makes the line meaningful
`
